Update GitHub workflow example
The working directory is missing from your workflow file in this repository but stuck around in the README

With that working directory directive, molecule will fail with:

```
ERROR: 'molecule/*/molecule.yml' glob failed.  Exiting.
```